model {
  file: "model.sdf"
}
name: "TOWER_TUMBLING"
description: "TOWER TUMBLING\nStack the rods and discs according to color or make various patterns to create a tower without falling."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "4121"
}
annotations {
  key: "sku"
  value: "0412100"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
